language: php

php:
  - 5.5
  - 5.6
  - 7.0

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/test-reporter